---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

connectivity:
  allowlist:
    - "localhost"
    - "127.0.0.1"
    - "sawtone.site"
    - "homepage.sawtone.site"
    - "/.*\\.vercel\\.app/"
